### PR TITLE
Add esp32 support

### PR DESCRIPTION
**Pull request by ethancheez**
ESP32 uses FreeRTOS, so implement `sei()` in `HardwareRateDriver.cpp` to enable interrupts.

Also it doesn't have a built-in LED, so add a #ifdef LED_BUILTIN

### CODE REVIEW

**Comment by capsulecorplab** [comment]
Likewise with https://github.com/SterlingPeet/fprime-arduino/pull/12#issuecomment-1639629284, I also have a few ESP32's I wouldn't mind flashing fprime on; Let me know how one could assist with validating this PR

**Comment by capsulecorplab** [comment]
Just ran a build of @ethancheez's [esp32](https://github.com/ethancheez/fprime-arduino/tree/esp32) branch in the fprime-arduino-led-blinker project and encountered the following cmake error

Screenshot from 2023-07-23 13-18-42

Screenshots of the head commits in `fprime-arduino-led-blinker` and `fprime-arduino`...

Screenshot from 2023-07-23 13-20-32
Screenshot from 2023-07-23 13-19-47

**Comment by ethancheez** [comment]
> Just ran a build of @ethancheez's [esp32](https://github.com/ethancheez/fprime-arduino/tree/esp32) branch in the fprime-arduino-led-blinker project and encountered the following cmake error

The ESP32 does not have a built-in LED. The `fprime-arduino-led-blinker` project assumes the board you are using has a built-in LED, which is why you're running into that error. 

## Solution:
Change `DEF_LED_BUILTIN` to a random GPIO pin number, as noted [here](https://github.com/fprime-community/fprime-arduino-led-blinker/blob/main/docs/full-integration.md#configuring-the-gpio-driver)

For this board, you wont be able to physically see an LED blink unless you have an external LED. To confirm if your deployment is working without an LED, you would have to look at the `Events` tab of the GDS if the commands are being dispatched as well as look at the `Channels` tab to see if the Led telemetries are changing.

**Comment by capsulecorplab** [comment]
I tried `7` in place of `DEF_LED_BUILTIN`, but that still threw an error
Screenshot from 2023-07-23 15-26-35

**Comment by ethancheez** [comment]
> I tried `7` in place of `DEF_LED_BUILTIN`, but that still threw an error
> 
> Screenshot from 2023-07-23 15-26-35
> 
> 

My mistake, replace `Arduino::DEF_LED_BUILTIN` with a pin number. 

So it's just a number without `Arduino::`

**Comment by capsulecorplab** [comment]
> My mistake, replace `Arduino::DEF_LED_BUILTIN` with a pin number.
> 
> So it's just a number without `Arduino::`

that fixed it!

Screenshot from 2023-07-23 15-41-10

**Comment by capsulecorplab** [comment]
Now I just need to debug why my ESP32 device isn't showing up as a serial port (s.a., `/dev/ttyACM0`)...

**Pull request closed without merging**
