### PR TITLE
Add rp2040 RPi Pico W support

### PR DESCRIPTION
**Pull request by ethancheez**

### CODE REVIEW

**Comment by capsulecorplab** [comment]
I recently bought a few RPI Pico W's, specifically with the hopes that someone would eventually add support for it on fprime, so I'd be happy to assist with validating this PR. Are there guidelines for how one could go about doing so?

**Comment by SterlingPeet** [comment]
> I recently bought a few RPI Pico W's, specifically with the hopes that someone would eventually add support for it on fprime, so I'd be happy to assist with validating this PR. Are there guidelines for how one could go about doing so?

Hello @capsulecorplab , At this moment the most useful thing you could do is try to see if you can compile a demo deployment with this platform, and comment with whatever issues you run into.  At the very least, the readme is sparse and may need some hints to get someone started using it.

**Comment by ethancheez** [comment]
> I recently bought a few RPI Pico W's, specifically with the hopes that someone would eventually add support for it on fprime, so I'd be happy to assist with validating this PR. Are there guidelines for how one could go about doing so?

@capsulecorplab @SterlingPeet 
I worked on a basic fprime LED blinker deployment for Arduino platforms. You can reference [this](https://github.com/fprime-community/fprime-arduino-led-blinker) to test new platforms such as the RPi Pico W.

**Comment by capsulecorplab** [comment]
@SterlingPeet @ethancheez Thanks for the pointers! I've gotten as far as building/running unit tests for the [workshop led blinker](https://github.com/fprime-community/fprime-workshop-led-blinker) project. I'm working on updating my [development environment](https://github.com/nasa/fprime/discussions/2141) with the arduino-cli tools for building the arduino-led-blinker project. Will post updates as I go~

**Comment by capsulecorplab** [comment]
Got the [Arduino CLI tools installed in (a branch of) my dev environment](https://github.com/users/capsulecorplab/packages/container/fprime-workspace-image/111306569?tag=install-arduino-cli-tools-for-building-arduino-led-blinker). I tried cloning the [fprime-arduino-led-blinker](https://github.com/fprime-community/fprime-arduino-led-blinker) and updating the `fprime-arduino` submodule to @ethancheez's [rpipicow](https://github.com/ethancheez/fprime-arduino/tree/rpipicow) branch and changing `teensy41` to `rpipicow` in `settings.ini`, but encountered a cmake error that `arduino-cli` and `rpipico:rpipicow` couldn't be found when attempting to run `fprime-util generate`, despite that it's installed

Screenshot from 2023-07-20 13-31-21
Screenshot from 2023-07-20 13-30-25
Screenshot from 2023-07-20 13-32-22

**Comment by ethancheez** [comment]
@capsulecorplab 
Did you add the following board manager:
```sh
arduino-cli config add board_manager.additional_urls https://github.com/earlephilhower/arduino-pico/releases/download/global/package_rp2040_index.json
```

And run:
```sh
arduino-cli core install rp2040:rp2040
```

**Comment by capsulecorplab** [comment]
> 

Yup, installed [here](https://github.com/capsulecorplab/fprime-workspace-image/commit/b8232c2f01dea2e347e95a5c657ba4e10f051be7#diff-d231edbab049480bb9012864178dcd0b9ccef7997ec46e14fc16ffe762b56f6cR291)

**Comment by capsulecorplab** [comment]
Also, I think I found the issue... I didn't reset the persistence layer in my VM, so it didn't populate the arduino workspace directory with the board packages, which explains why it didn't find it :sweat_smile:

**Comment by capsulecorplab** [comment]
Okay, I'm able run `fprime-util generate` now, but encountered the following when running `fprime-util build -j4`
Screenshot from 2023-07-20 14-51-56

**Comment by ethancheez** [comment]
@capsulecorplab
Right... I remember running into this. 

My workaroud was to comment out the `DEPRECATED` function in [`ActiveComponentBase.hpp:24`](https://github.com/nasa/fprime/blob/devel/Fw/Comp/ActiveComponentBase.hpp#L24).
And also the `start()` function in [`ActiveComponentBase.cpp:54`](https://github.com/nasa/fprime/blob/devel/Fw/Comp/ActiveComponentBase.cpp#L54)

These are deprecated functions which (should?) be removed from core F' eventually?

**Comment by capsulecorplab** [comment]
> My workaroud was to comment out the `DEPRECATED` function in [`ActiveComponentBase.hpp:24`](https://github.com/nasa/fprime/blob/devel/Fw/Comp/ActiveComponentBase.hpp#L24). And also the `start()` function in [`ActiveComponentBase.cpp:54`](https://github.com/nasa/fprime/blob/devel/Fw/Comp/ActiveComponentBase.cpp#L54)

That worked!

Screenshot from 2023-07-20 15-19-28

**Comment by capsulecorplab** [comment]
So full disclosure, it's my first time connecting a raspberry pi pico w to my (Linux Mint) desktop via usb cable... It shows up as a media device but I'm not seeing it on my list of devices with `ls /dev/tty*`. Any thoughts?

**Comment by ethancheez** [comment]
> So full disclosure, it's my first time connecting a raspberry pi pico w to my (Linux Mint) desktop via usb cable... It shows up as a media device but I'm not seeing it on my list of devices with `ls /dev/tty*`. Any thoughts?

If you run `arduino-cli board list`, does the pico appear in the list?

**Comment by capsulecorplab** [comment]
> > So full disclosure, it's my first time connecting a raspberry pi pico w to my (Linux Mint) desktop via usb cable... It shows up as a media device but I'm not seeing it on my list of devices with `ls /dev/tty*`. Any thoughts?
> 
> If you run `arduino-cli board list`, does the pico appear in the list?

No, but I would need to bind the device from my host machine to my virtual machine in order for that to work.

**Comment by capsulecorplab** [comment]
So, apparently the RP2040 doesn't ship with a serial port and only shows up as a mass storage device https://learn.adafruit.com/dude-where-s-my-com-port?view=all#rp2040-rom-bootloader-specific-3136942

**Comment by ethancheez** [comment]
> So, apparently the RP2040 doesn't ship with a serial port and only shows up as a mass storage device https://learn.adafruit.com/dude-where-s-my-com-port?view=all#rp2040-rom-bootloader-specific-3136942

Interesting, my Pico shows up as `/dev/ttyACM0` (Ubuntu). On Windows 10 it shows up as a COM port, and using WSL1, I can see the device at `/dev/ttyS10`. 

I can think of two ways to potentially solve this issue. 

# Method 1

I believe there should be a .UF2 file in your `build-artifacts/rpipicow/LedBlinker/bin`. Since your Pico appears as a media device, you may be able to drag and drop that file in there to program it. 

*Edit*: I just tried this and can confirm this works.

# Method 2

Here are the steps I did to acquire the upload command for the Pico W. Maybe you can try this and see if it works for you. 

1. Download the Arduino IDE
2. Add the json URL to the board manager under Preferences.
3. Install the RP2040 board under Board Manager
4. Enable verbose mode for compiling/uploading on your Arduino IDE
5. When you upload for the RPi Pico W, you should be able to see a command that calls an upload script on a .UF2 file. I basically copied that command. 

Also take a note if the port name appears when you select the Pico board on your IDE. Maybe it isn't `/dev/ttyACM0`

**Comment by capsulecorplab** [comment]
> # Method 1
> 
> I believe there should be a .UF2 file in your `build-artifacts/rpipicow/LedBlinker/bin`. Since your Pico appears as a media device, you may be able to drag and drop that file in there to program it.
> 
> _Edit_: I just tried this and can confirm this works.

I think this worked for me as well, as I'm now seeing a `/dev/ttyACM0` that I can bind to my VM. Though, ran into an argument error while trying to run the `fprime-gds` command from [LED Blinker: Running on Hardware](https://github.com/fprime-community/fprime-arduino-led-blinker/blob/main/docs/running-on-hardware.md#led-blinker-running-on-hardware
)

Screenshot from 2023-07-21 09-49-10

**Comment by ethancheez** [comment]
> Though, ran into an argument error while trying to run the `fprime-gds` command from [LED Blinker: Running on Hardware]

Run `pip install pyserial`

**Comment by capsulecorplab** [comment]
Also, there's no `build-artifacts/` folder after building with `fprime-util build -j4` in the `LedBlinker` folder. Should I be in the project root directory instead?
Screenshot from 2023-07-21 09-53-32

**Comment by ethancheez** [comment]
> Also, there's no `build-artifacts/` folder after building with `fprime-util build -j4` in the `LedBlinker` folder. Should I be in the project root directory instead?

Yes, I noted in [this issue](https://github.com/nasa/fprime/issues/2139#issuecomment-1644101128) (and [this](https://github.com/nasa/fprime/issues/2132#issuecomment-1644123437)) that we used the devel version of fprime-tools. So the `build-artifacts/` directory is in the project root instead of the deployment, and thus you run `fprime-gds` in the project root.

**Comment by capsulecorplab** [comment]
> > Also, there's no `build-artifacts/` folder after building with `fprime-util build -j4` in the `LedBlinker` folder. Should I be in the project root directory instead?
> 
> Yes, I noted in [this issue](https://github.com/nasa/fprime/issues/2139#issuecomment-1644101128) (and [this](https://github.com/nasa/fprime/issues/2132#issuecomment-1644123437)) that we used the devel version of fprime-tools. So the `build-artifacts/` directory is in the project root instead of the deployment, and thus you run `fprime-gds` in the project root.

Cool~ Opened an issue [here](https://github.com/fprime-community/fprime-arduino-led-blinker/issues/3) :slightly_smiling_face:

**Comment by capsulecorplab** [comment]
LED blinker's working!
Screenshot from 2023-07-21 13-14-02

**Comment by capsulecorplab** [comment]
Anything else I can test while I'm here? Communicating over WLAN perhaps?

**Comment by ethancheez** [comment]
> Anything else I can test while I'm here? Communicating over WLAN perhaps?

WLAN communication was definitely in my TODOs, especially since I got F' deployed on both the Pico W and ESP32, both of which have WiFi chips. If you are willing to create a WLAN component, that would be amazing! 

If you take a look at my [Baremetal Reference](https://github.com/fprime-community/fprime-baremetal-reference/tree/main), I am currently using a radio to wirelessly command an F' deployment. Think about it like a ground station talking to a satellite.
Now instead of using a radio component, replace it with a WLAN component, and theoretically we can use WiFi to communicate wirelessly between two WiFi chips!

**Comment by capsulecorplab** [comment]
> > Anything else I can test while I'm here? Communicating over WLAN perhaps?
> 
> WLAN communication was definitely in my TODOs, especially since I got F' deployed on both the Pico W and ESP32, both of which have WiFi chips. If you are willing to create a WLAN component, that would be amazing!
> 
> If you take a look at my [Baremetal Reference](https://github.com/fprime-community/fprime-baremetal-reference/tree/main), I am currently using a radio to wirelessly command an F' deployment. Think about it like a ground station talking to a satellite. Now instead of using a radio component, replace it with a WLAN component, and theoretically we can use WiFi to communicate wirelessly between two WiFi chips!

I probably haven't gone through enough fprime tutorials to know where to start with developing a WLAN component, so I'd need some guidance to tackle such a feature, to say the least. I recall getting the blinking led example working wirelessly with the  [RPI reference deployment](https://github.com/nasa/fprime/tree/devel/RPI) at one point - any chance we could reuse components from there?

**Comment by ethancheez** [comment]
> I probably haven't gone through enough fprime tutorials to know where to start with developing a WLAN component, so I'd need some guidance to tackle such a feature, to say the least. I recall getting the blinking led example working wirelessly with the [RPI reference deployment](https://github.com/nasa/fprime/tree/devel/RPI) at one point - any chance we could reuse components from there?

The RPi Ref deployment uses TCP/IP to communicate through a socket. These are currently implemented as [`Drv::TcpClient`](https://github.com/nasa/fprime/tree/devel/Drv/TcpClient), and a other libraries in [`fprime/Drv/Ip`](https://github.com/nasa/fprime/tree/devel/Drv/Ip). 

You would follow this structure since I believe the WiFi chip on the Pico W also uses sockets and the TCP/IP protocol. However the driver will most likely be different than the one in `fprime/Drv` since that is meant for Linux systems.

I would poke around some WLAN C++ libraries for the Pico W. The Arduino package might be a good start. For example, I found [this](https://dronebotworkshop.com/picow-arduino/#WiFi_Demo_Sketch) after a quick Google search.

**Comment by capsulecorplab** [comment]
Should the TCP/IP driver be a part of this PR or perhaps its own separate ticket+PR?

**Comment by capsulecorplab** [comment]
Also, should probably add a license #13 to the repo, so that we're not in violation of any copyrights owned by @SterlingPeet 🙃

**Comment by ethancheez** [comment]
> Should the TCP/IP driver be a part of this PR or perhaps its own separate ticket+PR?

A separate PR would be better.

**Comment by ethancheez** [comment]
@capsulecorplab 

TCP Client Driver has been made :)

It is under [`fprime-community/fprime-arduino` devel branch](https://github.com/fprime-community/fprime-arduino/tree/devel/Arduino/Drv/TcpClient)

I tested this with my Rpi Pico W and was successfully able to command it through the GDS. [Here](https://github.com/fprime-community/fprime-tutorial-arduino-blinker/tree/TcpClient) is an example of the implementation into the topology.

Also, when you start up the GDS, this is going to be your new command:
```
fprime-gds -n --dictionary build-artifacts/rpipicow/LedBlinker/dict/LedBlinkerTopologyAppDictionary.xml
```

You would need to start the GDS first, and then power on the Rpi Pico W.

**Comment by capsulecorplab** [comment]
@ethancheez sorry for the delay. Finally got around to compiling the arduino led blinker project with the tcp client driver (I think...). Though, I'm encountering an odd behavior when I try to drag and drop the .uf2 file into my rpi pico media storage device where it disconnects before it completes copying over. Any ideas?

**Comment by ethancheez** [comment]
> @ethancheez sorry for the delay. Finally got around to compiling the arduino led blinker project with the tcp client driver (I think...). Though, I'm encountering an odd behavior when I try to drag and drop the .uf2 file into my rpi pico media storage device where it disconnects before it completes copying over. Any ideas?

It only unmounts during the upload process? If you plug in the Pico with the BOOTSEL pressed down, wait for the media device to appear, leave it for a bit without uploading the .uf2 file, does it still unmount? If so, it could be a hardware issue. 

From my experience, the pico automatically unmounts after the .uf2 file is copied over.

Perhaps you can try the second upload method using the cli, does it succeed there?

If not, try upload a simple blink program using the Arduino IDE and see if that succeeds.

**Comment by capsulecorplab** [comment]
> It only unmounts during the upload process? If you plug in the Pico with the BOOTSEL pressed down, wait for the media device to appear, leave it for a bit without uploading the .uf2 file, does it still unmount? If so, it could be a hardware issue.

I haven't experienced it unmounting on its own; only while the .uf2 file is uploading.

> From my experience, the pico automatically unmounts after the .uf2 file is copied over.

If plugged back in, the .uf2 file doesn't appear alongside the other files.

> Perhaps you can try the second upload method using the cli, does it succeed there?

I haven't tried the 2nd method via the arduino-cli. Is it as simple as running `arduino-cli upload build-artifacts/rpipicow/LedBlinker/bin/LedBlinker.uf2`?

**Comment by ethancheez** [comment]
> If plugged back in, the .uf2 file doesn't appear alongside the other files.

If I recall correctly, the .uf2 file does not reappear in the media device after the upload completes.

> I haven't tried the 2nd method via the arduino-cli. Is it as simple as running arduino-cli upload build-artifacts/rpipicow/LedBlinker/bin/LedBlinker.uf2?

I have the instructions written [here](https://github.com/fprime-community/fprime-tutorial-arduino-blinker/blob/main/docs/uploading-to-board.md#raspberry-pi-pico-w-rp2040)

**Comment by capsulecorplab** [comment]
Right. I think I'd need to implement a serial bootloader on my Pico W, as it doesn't show up as a serial port https://learn.adafruit.com/dude-where-s-my-com-port?view=all#rp2040-rom-bootloader-specific-3136942; Maybe using something like https://github.com/usedbytes/rp2040-serial-bootloader

**Comment by capsulecorplab** [comment]
It's possible method 1 also worked, I'm just not able to connect to it with `fprime-gds`

**Comment by SterlingPeet** [comment]
If platform specific uploading tools or components need to be developed, that should probably be a separate development effort.

Sterling

Sent from my mobile.

On Aug 22, 2023, at 6:39 PM, Sean Marquez ***@***.***> wrote:

﻿

Right. I think I'd need to implement a serial bootloader on my Pico W, as it doesn't show up as a serial port https://learn.adafruit.com/dude-where-s-my-com-port?view=all#rp2040-rom-bootloader-specific-3136942; Maybe using something like https://github.com/usedbytes/rp2040-serial-bootloader

**Pull request closed without merging**
